name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build for iOS (latest simulator)
      run: |
        xcodebuild -scheme DateRangePicker -destination 'platform=iOS Simulator,name=iPhone,OS=latest' build
    - name: Run tests (latest simulator)
      run: |
        xcodebuild -scheme DateRangePicker -destination 'platform=iOS Simulator,name=iPhone,OS=latest' test